controller_manager:
  ros__parameters:
    update_rate: 100  # معدل التحديث بالهرتز

    # تعريف الكنترولرز اللي هتشتغل
    arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

# إعدادات ذراع الروبوت (Arm)
arm_controller:
  ros__parameters:
    joints:
      - joint1
      - joint2
    
    command_interfaces:
      - position

    state_interfaces:
      - position
      - velocity # ضفنا السرعة عشان الـ Feedback يكون أدق

    open_loop_control: true
    allow_integration_in_goal_trajectories: true